export enum MutationTypes {
  SET_BLOCK_HASH = 'SET_BLOCK_HASH',
  SET_BLOCK_NUMBER = 'SET_BLOCK_NUMBER',
  SET_EXTENSION_PRESENT = 'SET_EXTENSION_PRESENT',
  SET_EXTENSION_INITIALIZED = 'SET_EXTENSION_INITIALIZED',
  SET_SCREEN = 'SET_SCREEN',
}
